baseURL = 'https://thomasjakobsen.com'
languageCode = 'en-us'
title = 'Thomas Jakobsen'
summarylength = 30

[params]
title = "Thomas Jakobsen"
author = "Thomas Jakobsen"
description = "Sharing what helps me along the way 🚀"
profilePicture = "images/thomjak.png"
theme = "Anatole"
enableEmoji = true
readMore = true
singleDateFormat = "2006-01-02"
indexDateFormat = "2006-01-02"
listDateFormat = "2006-01-02"

[menu]
  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

[module]
  # uncomment line below for temporary local development of module
  # replacements = "github.com/lxndrblz/anatole -> ../../anatole"
  [[module.imports]]
    path = "github.com/lxndrblz/anatole"
    disable = false

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://linkedin.com/in/thomjak"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/thomjak"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "X.com"
url = "https://x.com/heisanthomas"

# [[params.socialIcons]]
# icon = "fab fa-instagram"
# title = "instagram"
# url = "https://www.instagram.com/"

